language: python
python:
- 2.7
- 3.3
- 3.4

sudo: false

install:
- pip install -r requirements.txt
- pip install -r dev-requirements.txt

script: 
- flake8 --version
- flake8 c2c --max-line-length=100
- python setup.py nosetests -a '!template'

after_success:
- pip install coveralls
- coveralls

notifications:
  email:
    on_failure: change

deploy:
- provider: pypi
  user: sbrunner
  password:
    secure: "kfcnO7uC+qIiG7xoK00FB/7xgMO7bLmAHjLqgpETXDA41VHWNhn8pMZJXxeY0fsNIQ/ETTHfVV0Di32hnvEnIKI/l4JUzPTPqrFKPRdwzpqHehrcxUOZXRSf2nOJd45w8ubnv/RLzfnUV/FMU9mK0smwiSNtIwk0G8SVEE59GxI="
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.4
    condition: '"${TRAVIS_TAG}" == "`python setup.py --version`"'
